# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Louis Hobbs
email: business@louishobbs.com
description: >- # this means to ignore newlines until "baseurl:"
  A very lovely description for my very work in progress website
twitter_username: bazzadwarf
github_username: bazzadwarf
minimal_mistakes_skin: mint
search: false
repository: Bazzadwarf/Bazzadwarf.github.io
# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 25 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Louis Hobbs"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Aspiring Game Developer and Designer.<br><br>Computer Games Programming graduate from the University of Derby Class of 2020."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bazzadwarf"
    - label: "Gitlab"
      icon: "fab fa-gitlab"
      url: "https://gitlab.com/bazzadwarf"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/louis-hobbs/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bazzadwarf"
    - label: "Gitlab"
      icon: "fab fa-gitlab"
      url: "https://gitlab.com/bazzadwarf"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/louis-hobbs/"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
